[firebase]
type = "service_account"
project_id = "projeto-integrador-5-41170"
private_key_id = "cee597be54f8ff5af83f9798fac0f35f0276dfd9"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQClFl5m/FPKqlM5
egGWM+DxxgLyoy4evhike5ga2d3/qXIhayAjk5BaGw6eSM0qVuEGc2PRtlJNtwsY
bXpTsAmsl7jZ6aN9qI1O/rIzb/pR4QbuD6th06sXTBqAuIWwnWMfix2qXwkCejcz
8G5WmjtCWg4mH2vQf/facIN4KGPHaoCfMBD/s4MoB6bpS8H/EJPiqw0+y9e5CfuX
k1Fxzo912nBEOkcfk3HGuE4Q1wJlw7d3qu7BIb6+10TTBA32Xdi1lXQf2RhgkFBG
/ZBqfvQCTf4LGO44Q9eAK0A8jjSjKa76YVhfN0CnxneSRfALsKu2925VjDRyD8HA
Uezs8daLAgMBAAECggEAAxy6V9+u5rWyTvWVXRMKTRSKDq/z2SGFTmiEFBGCZWT4
4VdnKjSIdqJm8qX1tDQiFuCLA7OXtp5aR7IcqcI6VHYhxn3olqBcVZ5olp6oTe3b
lxZViUkXwx8sqruPzaYR7dDOFN2oylKqgsCoG9rZfiU7eg2Cl1IqRoRzfgro4qQA
G0ruxIrAs5epTCvPpFdlTsHSMgi1wbL9yko0OBNtCK20mJUyzQuulHXpuFtCZt6G
O66d/7TKRk/JVI8ABhtSTpJB0luWa5UuqPTytXWDSylrUCEqUivyZRtDuQLFchTu
uDT4NKendQv+BDGwp5VSAGzaZ9N29yb+oJdEYkym9QKBgQDQGMQKSQJhFc9KFFrU
AtP2d4BCoxQnxLuvg2mq/3pCAElydODfMbCjxyrdmmxktWzKoc3ZuYlk7qWMqnIE
g99gOtC/+RzZuTrrsv6UNS95AEF2Mu6OJ+mPHL8FbkOzZ3Va3sMbEJxGVdUAMjAj
YRCm3/UkUZ8xghEWzez4Ki4i1QKBgQDLFwq7S/pUPxuwDwoKPKtVl0Zb/dkXKRdj
89cT5UwYZLu42uRBpkz4cgiwHzAhjBgfChwjXQG3wkyF1xIs217+WvMJLz/dcJxP
T5iyJvetbQaG5uGoNFnAPpxwnydKCz54i/yjiUXlw+pohYvVT/qMnGaB0c83pYNt
Y8GvVXUD3wKBgAxsvh/DFjJHxBWvO3EXLiK0JeNUq1pog7BKD2AXWuxf6gK8ecS5
ycstlCChHMGyl2lN2eWbD1oIabgJYT9lxEuRl28u54sUZTE3gb3Foyz9V+s/xUCV
n3tdAwbG+6HVlosza8DM8Be+/jXByWADZqQgERn3CaNCGdUbvH9gvVp1AoGAUY/f
b3kD//GYXQytK49R//3Q9ADuvq5yBmJXblYYSXOrMII4SWVQZDbn5lOgMNjilxSo
WEtx9SrDML0/P2Sasew0zut66qPfIrsEyAd+UNgIVwVCexsLMHn0ugYw8Tuyyxbt
T4BB4hTcfz2i+vgz12S4hkqMvfxq2/PERXY8mGECgYB84pSeBUM2IZoRF0UoErLW
ur3Qmngr1Km6g8VgiEPbRVhzRTmPj7fPXVcclUbir5VaX4zFSZZODUogQ5SGZydB
NYZkUc5hkkdrTUyhF+TQ+nWb9tu1nITtPxic0DXB9fSzxeJ874TEU2QoCEMERR4K
rGovOCb6ZyZmQMIyS8+cqg==
-----END PRIVATE KEY-----"""

client_email = "firebase-adminsdk-fbsvc@projeto-integrador-5-41170.iam.gserviceaccount.com"
client_id = "101079166416439839591"

auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"

auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40projeto-integrador-5-41170.iam.gserviceaccount.com"

universe_domain = "googleapis.com"
